---
title: "R Notebook"
output: html_notebook
---


```{r}
#importing and reading our merged data
```
```{r}
#library(rio)
#install_formats()
linkexcel='https://github.com/PUBPOL542G3/pythondeliverable-/raw/main/Triple_Merge.xlsx'
TM2_Data=import(linkexcel)
```


```{r}
#reseting the indexes to "R" format
```
```{r}
row.names(TM2_Data)=NULL
```


```{r}
#verifying the data structure
```
```{r}
str(TM2_Data,width = 50,strict.width='cut')
```


```{r}
#Stating our hypotheses
#Hypothesis 1: forest area increases as CO2 decreases
#Hypothesis 2: forest erea increases as employment & CO2 decrease
```
```{r}
hypo1=formula(forest_area~ CO2)
hypo2=formula(forest_area~ employment*CO2)
```


```{r}
#computing regression models
```
```{r}
gauss1=glm(hypo1,
           data = TM2_Data,
           family = 'gaussian')

gauss2=glm(hypo2,
           data = TM2_Data,
           family = 'gaussian')
```


```{r}
#displaying the results from regressional model 1
```
```{r}
summary(gauss1)
```


```{r}
#displaying the results from regressional model 2
```
```{r}
summary(gauss2)
```


```{r}
#searching for a better regression model
```
```{r}
anova(gauss1,gauss2,test="Chisq")
```


```{r}
#installing RSquared packages
#install.packages("rsq")
```
```{r}
library(rsq)
rsq(gauss2,adj=T)
```


```{r}
#installing required packages 
```
```{r}
install.packages("dotwhisker")
library(dotwhisker)
```


```{r}
#genearting summary plots and viewing the coefficient estimates
```
```{r}
dwplot(gauss2,by_2sd = F)
```


```{r}
#installing margins packages & plotting C02 again forest_area
```
```{r}
library(margins)
cplot(gauss2,'CO2')
```


```{r}
#plotting employment against forest_area
```
```{r}
cplot(gauss2,'employment')
```


```{r}
#plotting employment, C02 & forest area
```
```{r}
persp(gauss2)
```







